"""Seed data and idempotent bootstrap helpers."""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.dialects.sqlite import insert as sqlite_insert
from sqlalchemy.engine import Connection, Engine

from .database import benchmarks, models, scores, utc_now_iso

BENCHMARKS: list[dict[str, Any]] = [
    {
        "id": "aa_intelligence",
        "name": "AA Intelligence Index",
        "short": "AA Intel",
        "source": "Artificial Analysis",
        "url": "https://artificialanalysis.ai/leaderboards/models",
        "category": "General Quality",
        "metric": "Index Score",
        "higher_is_better": 1,
        "tier": 1,
        "scraper_id": "ArtificialAnalysisAdapter",
        "description": "Composite quality index across multiple tasks. Best single number for overall capability.",
        "active": 1,
    },
    {
        "id": "gpqa_diamond",
        "name": "GPQA Diamond",
        "short": "GPQA-D",
        "source": "Epoch AI",
        "url": "https://epoch.ai/benchmarks/gpqa-diamond",
        "category": "Reasoning & Math",
        "metric": "Accuracy %",
        "higher_is_better": 1,
        "tier": 2,
        "scraper_id": "EpochGpqaAdapter",
        "description": "Graduate-level science questions. Highly resistant to contamination.",
        "active": 1,
    },
    {
        "id": "mmmu",
        "name": "MMMU",
        "short": "MMMU",
        "source": "MMMU team",
        "url": "https://mmmu-benchmark.github.io/",
        "category": "Multimodal",
        "metric": "Accuracy %",
        "higher_is_better": 1,
        "tier": 2,
        "scraper_id": "MmmuAdapter",
        "description": "College-level multimodal questions across many subjects.",
        "active": 1,
    },
    {
        "id": "swebench_verified",
        "name": "SWE-bench Verified",
        "short": "SWE-V",
        "source": "SWE-bench team",
        "url": "https://www.swebench.com/",
        "category": "Coding",
        "metric": "% Issues Resolved",
        "higher_is_better": 1,
        "tier": 1,
        "scraper_id": "SwebenchAdapter",
        "description": "Real GitHub issue resolution. Strong coding benchmark for production relevance.",
        "active": 1,
    },
    {
        "id": "ifeval",
        "name": "IFEval",
        "short": "IFEval",
        "source": "Google Research",
        "url": "https://llm-stats.com/benchmarks/ifeval",
        "category": "Instruction Following",
        "metric": "Prompt Accuracy %",
        "higher_is_better": 1,
        "tier": 2,
        "scraper_id": "IfevalAdapter",
        "description": "Machine-scoreable instruction constraints. Predictive of enterprise reliability.",
        "active": 1,
    },
    {
        "id": "rag_groundedness",
        "name": "Vectara Hallucination Leaderboard",
        "short": "Vectara FC",
        "source": "Vectara",
        "url": "https://github.com/vectara/hallucination-leaderboard",
        "category": "Retrieval & Grounding",
        "metric": "Factual Consistency %",
        "higher_is_better": 1,
        "tier": 2,
        "scraper_id": "VectaraHallucinationAdapter",
        "description": "Factual consistency to provided source text. RAG-adjacent faithfulness signal, not retrieval relevance.",
        "active": 1,
    },
    {
        "id": "rag_task_faithfulness",
        "name": "FaithJudge",
        "short": "FaithJudge",
        "source": "Vectara",
        "url": "https://github.com/vectara/FaithJudge#leaderboard",
        "category": "Retrieval & Grounding",
        "metric": "Hallucination Rate %",
        "higher_is_better": 0,
        "tier": 2,
        "scraper_id": "FaithJudgeAdapter",
        "description": "Overall hallucination rate across RAG tasks on FaithBench and RagTruth. Lower is better.",
        "active": 1,
    },
    {
        "id": "terminal_bench",
        "name": "Terminal-Bench 2.0",
        "short": "Term-B",
        "source": "tbench.ai",
        "url": "https://www.tbench.ai/leaderboard/terminal-bench/2.0",
        "category": "Agentic & Tool Use",
        "metric": "% Tasks Resolved",
        "higher_is_better": 1,
        "tier": 2,
        "scraper_id": "TerminalBenchAdapter",
        "description": "Real workflow terminal tasks. Current policy derives one score per model from the best verified single-model submission.",
        "active": 1,
    },
    {
        "id": "ailuminate",
        "name": "AILuminate",
        "short": "Safety",
        "source": "MLCommons",
        "url": "https://ailuminate.mlcommons.org/benchmarks/",
        "category": "Safety & Compliance",
        "metric": "Grade (0-100)",
        "higher_is_better": 1,
        "tier": 1,
        "scraper_id": "AILuminateAdapter",
        "description": "Private test sets. English/French results are public HTML; other families remain anonymized.",
        "active": 1,
    },
    {
        "id": "aa_speed",
        "name": "Output Speed",
        "short": "Speed",
        "source": "Artificial Analysis",
        "url": "https://artificialanalysis.ai/leaderboards/models",
        "category": "Latency & Cost",
        "metric": "Tokens/sec",
        "higher_is_better": 1,
        "tier": 1,
        "scraper_id": "ArtificialAnalysisAdapter",
        "description": "Output tokens per second. Critical for real-time and high-concurrency systems.",
        "active": 1,
    },
    {
        "id": "aa_cost",
        "name": "Cost (blended)",
        "short": "Cost",
        "source": "Artificial Analysis",
        "url": "https://artificialanalysis.ai/leaderboards/models",
        "category": "Latency & Cost",
        "metric": "$/1M tokens",
        "higher_is_better": 0,
        "tier": 1,
        "scraper_id": "ArtificialAnalysisAdapter",
        "description": "Blended 3:1 input-output pricing. Lower is better.",
        "active": 1,
    },
    {
        "id": "chatbot_arena",
        "name": "Chatbot Arena",
        "short": "Arena ELO",
        "source": "LMSYS",
        "url": "https://arena.ai/leaderboard/text",
        "category": "General Quality",
        "metric": "ELO Score",
        "higher_is_better": 1,
        "tier": 1,
        "scraper_id": "ChatbotArenaAdapter",
        "description": "ELO from blind human preference votes.",
        "active": 1,
    },
]

MODELS: list[dict[str, Any]] = [
    {
        "id": "gemini-3-1-pro",
        "name": "Gemini 3.1 Pro Preview",
        "provider": "Google",
        "type": "proprietary",
        "release_date": "2026-Q1",
        "context_window": "1M tokens",
        "active": 1,
    },
    {
        "id": "gpt-5-4",
        "name": "GPT-5.4 (xhigh)",
        "provider": "OpenAI",
        "type": "proprietary",
        "release_date": "2026-Q1",
        "context_window": "128k tokens",
        "active": 1,
    },
    {
        "id": "gpt-5-3-codex",
        "name": "GPT-5.3 Codex (xhigh)",
        "provider": "OpenAI",
        "type": "proprietary",
        "release_date": "2026-Q1",
        "context_window": "128k tokens",
        "active": 1,
    },
    {
        "id": "claude-opus-4-6",
        "name": "Claude Opus 4.6",
        "provider": "Anthropic",
        "type": "proprietary",
        "release_date": "2025",
        "context_window": "200k tokens",
        "active": 1,
    },
    {
        "id": "claude-sonnet-4-6",
        "name": "Claude Sonnet 4.6",
        "provider": "Anthropic",
        "type": "proprietary",
        "release_date": "2025",
        "context_window": "200k tokens",
        "active": 1,
    },
    {
        "id": "o4-mini-high",
        "name": "o4 Mini High",
        "provider": "OpenAI",
        "type": "proprietary",
        "release_date": "2025",
        "context_window": "128k tokens",
        "active": 1,
    },
    {
        "id": "glm-5",
        "name": "GLM-5 (Reasoning)",
        "provider": "Zhipu AI",
        "type": "open_weights",
        "release_date": "2026-Q1",
        "context_window": "128k tokens",
        "active": 1,
    },
    {
        "id": "gemini-2-5-flash",
        "name": "Gemini 2.5 Flash-Lite (Reasoning)",
        "provider": "Google",
        "type": "proprietary",
        "release_date": "2025",
        "context_window": "1M tokens",
        "active": 1,
    },
    {
        "id": "mercury-2",
        "name": "Mercury 2",
        "provider": "Inception Labs",
        "type": "proprietary",
        "release_date": "2026-Q1",
        "context_window": "32k tokens",
        "active": 1,
    },
    {
        "id": "gemma-3n-e4b",
        "name": "Gemma 3n E4B Instruct",
        "provider": "Google",
        "type": "open_weights",
        "release_date": "2026-Q1",
        "context_window": "8k tokens",
        "active": 1,
    },
]

USE_CASES: list[dict[str, Any]] = [
    {
        "id": "general_reasoning",
        "label": "General Reasoning",
        "icon": "🧠",
        "description": "Logic, multi-step problem solving, knowledge-intensive tasks",
        "segment": "core",
        "status": "ready",
        "min_coverage": 0.5,
        "required_benchmarks": ["gpqa_diamond"],
        "benchmark_notes": {
            "gpqa_diamond": "Hard factual reasoning and exam-style problem solving.",
            "chatbot_arena": "User-facing helpfulness and response quality context.",
            "aa_intelligence": "Broad capability proxy for general model strength.",
        },
        "weights": {"aa_intelligence": 0.40, "gpqa_diamond": 0.35, "chatbot_arena": 0.25},
    },
    {
        "id": "coding",
        "label": "Coding & Engineering",
        "icon": "💻",
        "description": "Code generation, debugging, repo-level tasks, DevOps",
        "segment": "core",
        "status": "ready",
        "min_coverage": 0.45,
        "required_benchmarks": ["swebench_verified", "terminal_bench"],
        "benchmark_notes": {
            "swebench_verified": "Repo-level bug fixing and code-change execution.",
            "terminal_bench": "Agent-derived workflow evidence from verified single-model submissions.",
            "aa_intelligence": "General capability proxy for coding-adjacent reasoning.",
        },
        "weights": {"swebench_verified": 0.55, "aa_intelligence": 0.25, "terminal_bench": 0.20},
    },
    {
        "id": "agentic",
        "label": "Agentic & Tool Use",
        "icon": "🤖",
        "description": "Multi-step workflows, API calls, terminal and browser automation",
        "segment": "core",
        "status": "ready",
        "min_coverage": 0.5,
        "required_benchmarks": ["terminal_bench", "swebench_verified"],
        "benchmark_notes": {
            "terminal_bench": "Agent-derived workflow evidence from verified single-model submissions.",
            "swebench_verified": "Tool-using repo-level execution under realistic constraints.",
            "aa_intelligence": "General capability proxy for planning and reasoning.",
        },
        "weights": {"terminal_bench": 0.50, "swebench_verified": 0.25, "aa_intelligence": 0.25},
    },
    {
        "id": "safety_compliance",
        "label": "Safety & Compliance",
        "icon": "🛡️",
        "description": "Harmful output avoidance, hazard categories, regulatory readiness",
        "segment": "core",
        "status": "ready",
        "min_coverage": 0.5,
        "required_benchmarks": ["ailuminate"],
        "benchmark_notes": {
            "ailuminate": "Safety and hazard-resistance coverage for enterprise deployment readiness.",
            "aa_intelligence": "General capability context alongside safety.",
        },
        "weights": {"ailuminate": 0.70, "aa_intelligence": 0.30},
    },
    {
        "id": "cost_efficiency",
        "label": "Cost Efficiency",
        "icon": "💰",
        "description": "Minimise spend while maintaining quality for high-volume use",
        "segment": "core",
        "status": "ready",
        "min_coverage": 0.5,
        "required_benchmarks": ["aa_cost", "aa_speed"],
        "benchmark_notes": {
            "aa_cost": "Unit economics and spend per generated output.",
            "aa_speed": "Throughput and latency under load.",
            "aa_intelligence": "Quality context so low cost does not hide weak capability.",
        },
        "weights": {"aa_cost": 0.60, "aa_speed": 0.25, "aa_intelligence": 0.15},
    },
    {
        "id": "multimodal",
        "label": "Multimodal",
        "icon": "🖼️",
        "description": "Vision-language, chart understanding, document image processing",
        "segment": "core",
        "status": "ready",
        "min_coverage": 0.5,
        "required_benchmarks": ["mmmu"],
        "benchmark_notes": {
            "mmmu": "Document, chart, and image reasoning signal for multimodal enterprise work.",
            "aa_intelligence": "General capability context for multimodal selection.",
        },
        "weights": {"mmmu": 0.65, "aa_intelligence": 0.35},
    },
    {
        "id": "instruction_following",
        "label": "Instruction Following",
        "icon": "📋",
        "description": "Strict adherence to constraints, formatting rules, complex prompt structures",
        "segment": "core",
        "status": "ready",
        "min_coverage": 0.5,
        "required_benchmarks": ["ifeval"],
        "benchmark_notes": {
            "ifeval": "Constraint-following and formatting obedience.",
            "chatbot_arena": "Helpfulness and response quality context.",
        },
        "weights": {"ifeval": 0.75, "chatbot_arena": 0.25},
    },
    {
        "id": "speed",
        "label": "Speed / Latency",
        "icon": "⚡",
        "description": "Maximum throughput for real-time, streaming, or high-concurrency apps",
        "segment": "core",
        "status": "ready",
        "min_coverage": 0.5,
        "required_benchmarks": ["aa_speed"],
        "benchmark_notes": {
            "aa_speed": "Throughput and latency under production-like load.",
            "aa_intelligence": "Quality context so the fastest model is not selected blindly.",
        },
        "weights": {"aa_speed": 0.80, "aa_intelligence": 0.20},
    },
    {
        "id": "enterprise_automation",
        "label": "Enterprise Automation",
        "icon": "🏢",
        "description": "Internal copilots, workflow execution, ticket triage, and system actions under enterprise constraints",
        "segment": "enterprise",
        "status": "preview",
        "min_coverage": 0.55,
        "required_benchmarks": ["terminal_bench", "ifeval", "ailuminate"],
        "benchmark_notes": {
            "terminal_bench": "Agent-derived workflow evidence from verified single-model submissions.",
            "ifeval": "Instruction fidelity under structured enterprise prompts.",
            "ailuminate": "Safety and policy compliance under enterprise guardrails.",
            "aa_intelligence": "General capability context.",
            "aa_cost": "Operational spend for high-volume automation.",
            "aa_speed": "Latency for interactive workflows.",
        },
        "weights": {
            "terminal_bench": 0.35,
            "ifeval": 0.20,
            "ailuminate": 0.15,
            "aa_intelligence": 0.15,
            "aa_cost": 0.10,
            "aa_speed": 0.05,
        },
    },
    {
        "id": "customer_support",
        "label": "Customer Support",
        "icon": "🎧",
        "description": "Service desk chat, escalation handling, response quality, safety, and operating cost at scale",
        "segment": "enterprise",
        "status": "preview",
        "min_coverage": 0.5,
        "required_benchmarks": ["chatbot_arena", "ifeval", "ailuminate"],
        "benchmark_notes": {
            "chatbot_arena": "Preference and conversational quality for support-style interactions.",
            "ifeval": "Ability to obey policy and format constraints in scripted support flows.",
            "ailuminate": "Safety and refusal quality for customer-facing deployments.",
            "aa_cost": "Unit economics for support at scale.",
            "aa_speed": "Latency for interactive service conversations.",
        },
        "weights": {
            "chatbot_arena": 0.30,
            "ifeval": 0.25,
            "ailuminate": 0.20,
            "aa_cost": 0.15,
            "aa_speed": 0.10,
        },
    },
    {
        "id": "document_operations",
        "label": "Document Operations",
        "icon": "🗂️",
        "description": "Document review, form extraction, policy QA, and visual enterprise content workflows",
        "segment": "enterprise",
        "status": "ready",
        "min_coverage": 0.5,
        "required_benchmarks": ["mmmu", "ifeval"],
        "benchmark_notes": {
            "mmmu": "Vision-language and document reasoning for forms, charts, and screenshots.",
            "ifeval": "Structured instruction following for extraction and policy QA.",
            "aa_intelligence": "General capability context for mixed document tasks.",
            "ailuminate": "Safety and compliance context when document content is sensitive.",
            "aa_speed": "Throughput for bulk processing.",
        },
        "weights": {
            "mmmu": 0.35,
            "ifeval": 0.25,
            "aa_intelligence": 0.20,
            "ailuminate": 0.10,
            "aa_speed": 0.10,
        },
    },
    {
        "id": "knowledge_work_rag_sorting",
        "label": "Knowledge Work / RAG Retrieval Sorting",
        "icon": "🔎",
        "description": "Retrieval sorting, context ranking, and grounded answer shaping around retrieved context",
        "segment": "enterprise",
        "status": "preview",
        "min_coverage": 0.55,
        "required_benchmarks": ["rag_groundedness", "rag_task_faithfulness", "ifeval"],
        "benchmark_notes": {
            "rag_groundedness": "Vectara factual consistency to supplied source text. RAG-adjacent faithfulness signal, not retrieval relevance.",
            "rag_task_faithfulness": "FaithJudge direct hallucination rate across RAG tasks on supplied contexts. Lower is better, but it still does not measure retrieval relevance.",
            "ifeval": "Instruction fidelity for organizing, ranking, and shaping retrieved context.",
            "aa_intelligence": "General capability context for synthesis and analysis once retrieval is assembled.",
            "chatbot_arena": "Answer quality after retrieval is assembled.",
        },
        "weights": {
            "rag_task_faithfulness": 0.35,
            "rag_groundedness": 0.25,
            "ifeval": 0.15,
            "aa_intelligence": 0.15,
            "chatbot_arena": 0.10,
        },
    },
    {
        "id": "governed_enterprise_rollout",
        "label": "Governed Enterprise Rollout",
        "icon": "📜",
        "description": "Regulated deployment, procurement, and risk-sensitive rollout decisions",
        "segment": "enterprise",
        "status": "ready",
        "min_coverage": 0.5,
        "required_benchmarks": ["ailuminate"],
        "benchmark_notes": {
            "ailuminate": "Primary safety and policy compliance evidence for regulated deployment.",
            "ifeval": "Structured instruction following for policy and rollout controls.",
            "aa_intelligence": "General capability context for procurement tradeoffs.",
            "aa_cost": "Operational spend and vendor economics.",
        },
        "weights": {
            "ailuminate": 0.40,
            "ifeval": 0.25,
            "aa_intelligence": 0.20,
            "aa_cost": 0.15,
        },
    },
    {
        "id": "developer_platform_agent",
        "label": "Developer Platform Agent",
        "icon": "🧩",
        "description": "Internal engineering automation, repo tasks, and CI/CD support",
        "segment": "enterprise",
        "status": "preview",
        "min_coverage": 0.55,
        "required_benchmarks": ["terminal_bench", "swebench_verified"],
        "benchmark_notes": {
            "terminal_bench": "Agent-derived workflow evidence for terminal and tool execution.",
            "swebench_verified": "Repo-level bug fixing and code-change execution.",
            "ifeval": "Instruction fidelity for build, deploy, and change-management steps.",
            "aa_intelligence": "General reasoning context for engineering workflows.",
        },
        "weights": {
            "terminal_bench": 0.40,
            "swebench_verified": 0.30,
            "ifeval": 0.15,
            "aa_intelligence": 0.15,
        },
    },
    {
        "id": "workflow_automation",
        "label": "Workflow Automation",
        "icon": "🔁",
        "description": "Back-office automation, queue handling, and multi-step ops workflows",
        "segment": "enterprise",
        "status": "preview",
        "min_coverage": 0.55,
        "required_benchmarks": ["terminal_bench", "ifeval"],
        "benchmark_notes": {
            "terminal_bench": "Agent-derived workflow evidence for multi-step execution.",
            "ifeval": "Structured instruction following for operational procedures.",
            "ailuminate": "Safety and guardrails for actions that touch business systems.",
            "aa_cost": "Operating cost for high-volume workflow execution.",
            "aa_speed": "Latency and throughput for queue-driven work.",
        },
        "weights": {
            "terminal_bench": 0.35,
            "ifeval": 0.20,
            "ailuminate": 0.20,
            "aa_cost": 0.15,
            "aa_speed": 0.10,
        },
    },
    {
        "id": "small_model_routing",
        "label": "Small-Model Routing",
        "icon": "🌱",
        "description": "When to use small, fast, and cheap models for triage and first-pass work",
        "segment": "enterprise",
        "status": "ready",
        "min_coverage": 0.5,
        "required_benchmarks": ["aa_cost", "aa_speed"],
        "benchmark_notes": {
            "aa_cost": "Primary economic signal for cheap first-pass routing.",
            "aa_speed": "Latency and throughput for triage and extraction.",
            "ifeval": "Reliability for formatting, extraction, and routing rules.",
            "chatbot_arena": "Output quality when a small model handles first-pass work.",
            "ailuminate": "Guardrails so routing choices stay safe in enterprise settings.",
        },
        "weights": {
            "aa_cost": 0.35,
            "aa_speed": 0.30,
            "ifeval": 0.20,
            "chatbot_arena": 0.10,
            "ailuminate": 0.05,
        },
    },
]

AILUMINATE_GRADE_TO_SCORE: dict[str, float] = {
    "Poor": 0.0,
    "Fair": 25.0,
    "Good": 50.0,
    "VeryGood": 75.0,
    "Very Good": 75.0,
    "Excellent": 100.0,
}

SEED_SCORES: list[dict[str, Any]] = [
    {"model_id": "gemini-3-1-pro", "benchmark_id": "aa_intelligence", "value": 57.0, "raw_value": "57"},
    {"model_id": "gpt-5-4", "benchmark_id": "aa_intelligence", "value": 57.0, "raw_value": "57"},
    {"model_id": "gpt-5-3-codex", "benchmark_id": "aa_intelligence", "value": 54.0, "raw_value": "54"},
    {"model_id": "claude-opus-4-6", "benchmark_id": "aa_intelligence", "value": 53.0, "raw_value": "53"},
    {"model_id": "claude-sonnet-4-6", "benchmark_id": "aa_intelligence", "value": 52.0, "raw_value": "52"},
    {"model_id": "glm-5", "benchmark_id": "aa_intelligence", "value": 50.0, "raw_value": "50"},
    {"model_id": "gemini-3-1-pro", "benchmark_id": "gpqa_diamond", "value": 94.1, "raw_value": "94.1%"},
    {"model_id": "gpt-5-4", "benchmark_id": "gpqa_diamond", "value": 92.0, "raw_value": "92.0%"},
    {"model_id": "gpt-5-3-codex", "benchmark_id": "gpqa_diamond", "value": 91.5, "raw_value": "91.5%"},
    {
        "model_id": "claude-opus-4-6",
        "benchmark_id": "gpqa_diamond",
        "value": 91.3,
        "raw_value": "~91.3%",
        "source_type": "secondary",
        "verified": 0,
        "notes": "From aggregator - verify against primary",
    },
    {"model_id": "o4-mini-high", "benchmark_id": "mmmu", "value": 79.2, "raw_value": "79.2%"},
    {"model_id": "gpt-5-4", "benchmark_id": "mmmu", "value": 79.1, "raw_value": "79.1%"},
    {
        "model_id": "claude-opus-4-6",
        "benchmark_id": "swebench_verified",
        "value": 80.8,
        "raw_value": "80.8%",
        "source_type": "secondary",
        "verified": 0,
    },
    {
        "model_id": "gemini-3-1-pro",
        "benchmark_id": "swebench_verified",
        "value": 80.6,
        "raw_value": "80.6%",
        "source_type": "secondary",
        "verified": 0,
    },
    {
        "model_id": "claude-sonnet-4-6",
        "benchmark_id": "swebench_verified",
        "value": 79.6,
        "raw_value": "79.6%",
        "source_type": "secondary",
        "verified": 0,
    },
    {
        "model_id": "glm-5",
        "benchmark_id": "swebench_verified",
        "value": 77.8,
        "raw_value": "77.8%",
        "source_type": "secondary",
        "verified": 0,
    },
    {
        "model_id": "gemini-3-1-pro",
        "benchmark_id": "terminal_bench",
        "value": 78.4,
        "raw_value": "78.4%",
        "source_type": "secondary",
        "verified": 0,
    },
    {
        "model_id": "gpt-5-3-codex",
        "benchmark_id": "terminal_bench",
        "value": 77.3,
        "raw_value": "77.3%",
        "source_type": "secondary",
        "verified": 0,
    },
    {
        "model_id": "claude-opus-4-6",
        "benchmark_id": "terminal_bench",
        "value": 74.7,
        "raw_value": "74.7%",
        "source_type": "secondary",
        "verified": 0,
    },
    {
        "model_id": "glm-5",
        "benchmark_id": "ifeval",
        "value": 88.0,
        "raw_value": "88.0%",
        "source_type": "secondary",
        "verified": 0,
    },
    {
        "model_id": "glm-5",
        "benchmark_id": "chatbot_arena",
        "value": 1451.0,
        "raw_value": "1451",
        "source_type": "secondary",
        "verified": 0,
    },
    {"model_id": "mercury-2", "benchmark_id": "aa_speed", "value": 789.2, "raw_value": "789.2 t/s"},
    {"model_id": "gemini-2-5-flash", "benchmark_id": "aa_speed", "value": 386.1, "raw_value": "386.1 t/s"},
    {"model_id": "gemma-3n-e4b", "benchmark_id": "aa_cost", "value": 0.03, "raw_value": "$0.03/1M"},
]


def _has_rows(conn: Connection, table) -> bool:
    count = conn.execute(select(func.count()).select_from(table)).scalar_one()
    return bool(count)


def _upsert_rows(conn: Connection, table, rows: Iterable[Mapping[str, Any]]) -> None:
    rows_list = list(rows)
    if not rows_list:
        return

    stmt = sqlite_insert(table).values(rows_list)
    update_columns = {
        column.name: getattr(stmt.excluded, column.name)
        for column in table.columns
        if column.name != "id"
    }
    stmt = stmt.on_conflict_do_update(index_elements=["id"], set_=update_columns)
    conn.execute(stmt)


def seed_reference_data(target: Connection | Engine, *, include_seed_scores: bool = False) -> None:
    if isinstance(target, Engine):
        with target.begin() as conn:
            seed_reference_data(conn, include_seed_scores=include_seed_scores)
        return

    conn = target
    _upsert_rows(conn, benchmarks, BENCHMARKS)
    _upsert_rows(conn, models, MODELS)

    if include_seed_scores and not _has_rows(conn, scores):
        collected_at = "2026-03-31T00:00:00Z"
        rows = []
        for row in SEED_SCORES:
            payload = dict(row)
            payload.setdefault("source_type", "primary")
            payload.setdefault("verified", 1)
            payload.setdefault("source_url", None)
            payload.setdefault("notes", None)
            payload.setdefault("collected_at", collected_at)
            rows.append(payload)
        conn.execute(scores.insert(), rows)


__all__ = [
    "AILUMINATE_GRADE_TO_SCORE",
    "BENCHMARKS",
    "MODELS",
    "SEED_SCORES",
    "USE_CASES",
    "seed_reference_data",
]
